### ISSUE TITLE
Create option to override HTTP client

### ISSUE THREAD

**Issue by mathcass** [motemen/go-pocket#6]
It's an honor to virtually meet you. I ran into an issue using this library on Google appengine, where it's [required](https://cloud.google.com/appengine/docs/standard/go/issue-requests) to use a different HTTP client. The conventional way to do this would be to offer the caller of the library to set his or her own client. Here's [an example](https://github.com/mailgun/mailgun-go/blob/39996ba7228e34ce3f33762777eaa6f2dcc47fe1/mailgun.go#L281-L284) of that in the wild.

**Comment by motemen** [comment]
Closing by https://github.com/motemen/go-pocket/pull/5 .
